# Generated by Django 5.0.4 on 2024-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='generated_content',
            field=models.CharField(max_length=5000),
        ),
    ]
