# Generated by Django 5.0.4 on 2024-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0002_alter_blogpost_generated_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='generated_content',
            field=models.CharField(max_length=1024),
        ),
    ]
